spring:
  application:
    name: bussiness-service
  datasource:
    url: jdbc:mysql://112.74.106.151:3306/seata?useInformationSchema=false&allowMultiQueries=true
    username: root
    password: mynameis__zhang5122
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        applicationId: bussiness-service
        tx-service-group: my_test_tx_group
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: info
server:
  port: 8084